# github pages
# url: /
# baseurl: /quijote
# dev
url: /

name: Cómo ser un quijote
author: Bronson Duhart
intro: Viajes. Aventuras. Arte. Cartas y locuras.
# intro: Mi viaje personal por la vida, documentado a través de letras e imágenes.
about: |
  This is the template for my blog. Right now, you are reading the about section of it. Welcome and please enjoy my super nice blog. I will now include some nonsense ipsum to fill space.

  Un día alguien me aconsejó que escribiera, y no he parado de hacerlo desde entonces.

ga_id: UA-153237091-1

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      permalink: /:year/:month/:day/:title
      excerpt_separator: <!-- more -->

show_drafts: false
future: false
markdown: kramdown
